name: Update Prices
on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4 pytz

      - name: Run parser
        run: |
          python -c "from app import run_parsing; run_parsing()"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add price_history.json last_run.json
          git commit -m "Auto-update prices" || exit 0
          git push
