name: Hourly Price Check

on:
  schedule:
    - cron: '0 * * * *'  # Запуск в 00 минут каждого часа
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4 pytz lxml

      - name: Run parser
        run: python app.py --parse

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add price_history.json last_run.json
          git commit -m "Hourly price update" || echo "No changes to commit"
          git push
